package com.dataloom.checklist.domain.usecase

import com.dataloom.checklist.domain.model.ChecklistId
import com.dataloom.checklist.domain.model.ChecklistItem
import com.dataloom.checklist.domain.model.ChecklistItemId
import com.dataloom.checklist.domain.model.ChecklistItemUpdate
import com.dataloom.checklist.domain.model.MasterItemId
import com.dataloom.checklist.domain.model.NewChecklistItem
import com.dataloom.checklist.domain.model.Quantity
import com.dataloom.checklist.domain.model.SectionId
import com.dataloom.checklist.domain.model.UnitCode
import com.dataloom.checklist.domain.repository.CatalogRepository
import com.dataloom.checklist.domain.repository.ChecklistRepository
import com.dataloom.checklist.domain.validation.ValidationError
import com.dataloom.checklist.domain.validation.ValidationResult
import javax.inject.Inject

sealed interface CustomItemOutcome {
    /** [masterItemId] is set when the item was saved to (or matched) the master list. */
    data class Added(val itemId: ChecklistItemId, val masterItemId: MasterItemId?) : CustomItemOutcome

    /**
     * "Save to suggestions" matched a master item that is already in this section; nothing was
     * added so the UI can offer "Increase quantity instead?".
     */
    data class AlreadyPresent(val existing: ChecklistItem) : CustomItemOutcome
}

/**
 * Adds an item the user typed. With [saveToMasterList] the name also becomes a suggestion in the
 * section's category; an existing master item with the same name is reused rather than duplicated,
 * and the new checklist item links to it so ranking and "already present" checks keep working.
 */
class AddCustomItemUseCase @Inject constructor(
    private val checklists: ChecklistRepository,
    private val catalog: CatalogRepository,
) {
    @Suppress("LongParameterList") // Mirrors the "Create new item" form one-to-one.
    suspend operator fun invoke(
        checklistId: ChecklistId,
        sectionId: SectionId,
        name: String,
        locale: String,
        quantity: Quantity? = null,
        unit: UnitCode? = null,
        notes: String? = null,
        saveToMasterList: Boolean = false,
    ): DomainResult<CustomItemOutcome> {
        val fields = when (val result = catalog.validateItem(name, quantity, unit, notes)) {
            is ValidationResult.Invalid -> return result.toFailure()
            is ValidationResult.Valid -> result.value
        }
        val section = checklists.findSection(checklistId, sectionId) ?: return failure(DomainError.NotFound)

        var masterItemId: MasterItemId? = null
        var canonicalKey: String? = null
        if (saveToMasterList) {
            val categoryId = section.category.id
            val match = catalog.findMasterItemByName(categoryId, fields.name, locale)
            if (match != null) {
                section.items.firstOrNull { it.masterItemId == match.id }?.let {
                    return success(CustomItemOutcome.AlreadyPresent(it))
                }
                masterItemId = match.id
                canonicalKey = match.canonicalKey
            } else {
                // The new master item's "custom:<uuid>" key is generated by :data and not returned,
                // so the snapshot keeps only the back-reference; the name is what the user sees.
                masterItemId = catalog.createMasterItem(categoryId, fields.name, locale, fields.unit)
            }
        }

        val item = NewChecklistItem(
            masterItemId = masterItemId,
            canonicalKey = canonicalKey,
            displayName = fields.name,
            displayNameLocale = locale,
            quantity = fields.quantity,
            unit = fields.unit,
            notes = fields.notes,
        )
        val itemId = checklists.addItems(sectionId, listOf(item)).single()
        return success(CustomItemOutcome.Added(itemId, masterItemId))
    }
}

/**
 * Saves the item editor. It takes the full desired state rather than a patch so the quantity and
 * unit rules can be checked together without reading the item first. A null [quantity] clears both
 * quantity and unit; blank [notes] clears the notes.
 */
class UpdateChecklistItemUseCase @Inject constructor(
    private val checklists: ChecklistRepository,
    private val catalog: CatalogRepository,
) {
    suspend operator fun invoke(
        itemId: ChecklistItemId,
        name: String,
        quantity: Quantity?,
        unit: UnitCode?,
        notes: String?,
    ): DomainResult<Unit> {
        val fields = when (val result = catalog.validateItem(name, quantity, unit, notes)) {
            is ValidationResult.Invalid -> return result.toFailure()
            is ValidationResult.Valid -> result.value
        }
        val update = ChecklistItemUpdate(
            displayName = fields.name,
            quantity = fields.quantity,
            unit = fields.unit,
            notes = fields.notes,
            clearQuantity = fields.quantity == null,
            clearNotes = fields.notes == null,
            clearUnit = fields.unit == null,
        )
        checklists.updateItem(itemId, update)
        return success(Unit)
    }
}

class SetItemCompletedUseCase @Inject constructor(private val checklists: ChecklistRepository) {
    suspend operator fun invoke(itemId: ChecklistItemId, completed: Boolean): DomainResult<Unit> =
        success(checklists.setItemCompleted(itemId, completed))
}

/** Destructive: the UI (and the AI executor) confirm first. */
class DeleteChecklistItemUseCase @Inject constructor(private val checklists: ChecklistRepository) {
    suspend operator fun invoke(itemId: ChecklistItemId): DomainResult<Unit> = success(checklists.deleteItem(itemId))
}

/** [toIndex] is the 0-based target position inside the item's section. */
class MoveItemUseCase @Inject constructor(private val checklists: ChecklistRepository) {
    suspend operator fun invoke(itemId: ChecklistItemId, toIndex: Int): DomainResult<Unit> {
        if (toIndex < 0) return failure(DomainError.Invalid(listOf(ValidationError.NEGATIVE_POSITION)))
        return success(checklists.moveItem(itemId, toIndex))
    }
}
